project:
  type: book
  output-dir: docs

book:
  title: "Statistical Analysis Using R: Online Notes"
  chapters:
    - index.qmd
    - inference.qmd
    - approximations.qmd
    - olsregression.qmd
    - robustness.qmd
    - features.qmd
    - modelselection.qmd
    - glms.qmd
    - binomialregression.qmd
    - countregression.qmd
    - multinomialregression.qmd
  appendices:
    - part: "Distributions"
      chapters: 
        - dist_bernoulli.qmd
        - dist_binomial.qmd
        - dist_chisquared.qmd
        - dist_exponential.qmd
        - dist_f.qmd
        - dist_geometric.qmd
        - dist_negativebinomial.qmd
        - dist_normal.qmd
        - dist_poisson.qmd
        - dist_t.qmd
        - dist_uniform.qmd
    - proofs.qmd
    - listofsymbols.qmd
 
format:
  bookup-html:
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    page-layout: full
    smooth-scroll: true
    
filters:
  - shinylive